### ISSUE TITLE
Compose Mail shows Upgrade Popup

### ISSUE THREAD

**Issue by aiknayan** [medartus/mailtrack-signature-remover#1]
Thought the extension removes Signature there's another popup arise after removing the signature. Requesting If possible to remove popup also.

**Comment by dipta007** [comment]
A PR is open for that: https://github.com/medartus/mailtrack-signature-remover/pull/2
Till not merged use this one: https://github.com/dipta007/mailtrack-signature-remover

**Comment by medartus** [comment]
Hi dipta007, thanks for your PR!

Resolving the issue.
